# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :systemd => {
        :box_name => "eXteZone/centos7vbg",
        :ip_addr => '192.168.11.101'
  }
}
Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
          end

	  box.vm.synced_folder ".", "/vagrant"
          
          box.vm.provision "shell", inline: <<-SHELL
          SHELL
          box.vm.provision "watchlog", type: "shell", path: "./scripts/watchlog-config.sh"
          box.vm.provision "httpd", type: "shell", path: "./scripts/httpd-config.sh"
      end
   end
end

