# -*- mode: ruby -*-
# vi: set ft=ruby :
# up server
dir = Dir.pwd
vagrant_dir = File.expand_path(File.dirname(__FILE__))

Vagrant.configure(2) do |config|
config.vbguest.auto_update = true
config.vm.box_check_update = true
box_name = "eXteZone/centos7vbg"
vm = {

        'systemd-server' => {
            :name => 'systemd-server',
            :ip => '192.168.89.99',
            :box => box_name
        }
    }
	
	vm.each do |key,value|

    boxname = value[:name]
    config.vm.provision :shell, inline: 'echo boxname: ' + boxname

    config.vm.define boxname do |vm_config|

        vm_config.vm.provision "shell", inline: "echo !!!NAME!!!! #{key}"
        vm_config.vm.provision "shell", inline: "echo !!!IP!!!! #{value[:ip]}"

        vm_config.vm.box = value[:box]
        vm_config.vm.host_name = "%s.vagrant" % value[:name]

        vm_config.vm.network "private_network", ip: value[:ip]

        vm_config.vm.provision "watchlog", type: "shell", path: "./scripts/watchlog-config.sh"
        vm.config.vm.provision "httpd", type: "shell", path: "./scripts/httpd-config.sh"
        # Shared folder
        config.vm.synced_folder '.', '/vagrant'
end
end
end
